version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # nest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: nest-container
  #   depends_on:
  #     - postgres
  #   environment:
  #     DATABASE_URL: postgres://user:pwd@postgres:5432/mydb
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/app
  #   command: "npm run start:dev"

volumes:
  postgres_data:
