version: '3'

services:
  postgres_bank:
    image: postgres:latest
    container_name: postgres-container-bank
    environment:
      POSTGRES_USER: user_bank
      POSTGRES_PASSWORD: pwd_bank
      POSTGRES_DB: mydb_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_bank:/var/lib/postgresql/data

  nest_bank:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nest-container-bank
    depends_on:
      - postgres_bank
    environment:
      DATABASE_URL: postgres://user_bank:pwd_bank@postgres_bank:5432/mydb_bank
    ports:
      - "3000:3000"
    volumes:
      - .:/app_bank
    command: "npm run start:dev"

volumes:
  postgres_data_bank:
